In [2]:
import torch

In [3]:
if torch.cuda.is_available():
    print('On GPU')
else:
    print('Sorry, CPU only')

On GPU


after determining we have a GPU(s) available, we need to put our data where the GPU can see it. CPU performs computations on computers RAM. GPU has dedicated memory attached to it. WHenever you want to perform a cmputattion on a device, you must move *all* the data needed for that computation to memory accessible by that device. (moving the data to memory accessible by the GPU = moving the data to the GPU)

Multiple ways to move data to the GPU. At creation time:

In [4]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device='cuda')
  print(gpu_rand)
else:
  print('no gpu')

tensor([[0.3340, 0.2380],
        [0.1306, 0.9463]], device='cuda:0')


By default, new tensors are created on the CPU, so we have to specify when we want to create our tensor on the GPU with the optional ```device``` argument. Pytorch informs us which device it's on (if not on CPU)

We can query th number of GPU's with ```torch.cuda.dvice_count()```. If we have more than one GPU, we can specify them by index: ```device='cuda:0'```, ```device='cuda:1'```, etc

Specifying devices everywhere with string constants is fragile. We create a device handle that can be passed to our tensors instead of a string:

In [5]:
if torch.cuda.is_available():
  my_device = torch.device('cuda')
else:
  my_device = torch.device('cpu')
print('device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

device: cuda
tensor([[0.8352, 0.8573],
        [0.9296, 0.2123]], device='cuda:0')


If there is an existing tensor living on one device, you can move it to another with the ```to()``` method. The following line of code created a tensor on CPU, and moves it to whichever device handle you acquired in the previous cell.

In [6]:
y = torch.rand(2, 2)
y = y.to(my_device)
print(y)

tensor([[0.5743, 0.4909],
        [0.9951, 0.1492]], device='cuda:0')


In a computation involving two or more tensors, *all the tensors must be on the same device*:

In [7]:
x = torch.rand(2, 2,)
y = torch.rand(2, 2, device='gpu')
z = x + y   #except will be thrown

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, maia, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu