In [3]:
import torch

Ways to create tensors: 

In [5]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


This was a 5x3 matrix filled with zeroes, and query its datatype. the zeros inside the tensor are a 32-bit floating point numbers. this is the deafult PyTorch. 

Override the default with integers:

In [6]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


When we change the default, the tensor reports when printed. 

Common to initialize learning weights randomly, often with a specific seed for the PRNG for reproducibility of results: 

In [8]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2,2)
print("\nDifferent random tensor:")
print(r2) # new values 

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print('\nshould be same as r1:')
print(r3) # repeated values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

Different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

should be same as r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


Tensors perform arithmetic operations intuitively. Tensors of similar shaped may be added, multiplied, etc. Operations with scalars are distributed over the tensor:

arithmetic - Tensors with similar shapes may be added, multiplied, etc.. and a scalar and a tensor will distribute over all the cells of the tensor. 

In [ ]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3) * 2 # every element is multiplies by 2
print(twos)

threes = ones + twos # addition is okay because shapes are similar 
print(threes) #tensors are added element wise 
print(threes.shape)

r1 = torch.rand(2,3)
r2 = torch.rand(3,2)
r3 = r1 + r2 # not allowed, can't do element wise arithmetic with tensors of different shape 

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Sample of mathematical operations available:

In [25]:
r = torch.rand(2,2) - 0.5 * 2 # values between -1 and 1 
print('Random matrix r:')
print(r)

# common mathematical operations supported: 
print('\nabsolute value of r:')
print(torch.abs(r))

# as are trig functions 
print('\ninverse sine of r:')
print(torch.asin(r))

# linear alg operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition')
print(torch.svd(r))

# statistical and aggregat operations
print('\nAverage and standard devation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))


Random matrix r:
tensor([[-0.3507, -0.7367],
        [-0.5238, -0.9452]])

absolute value of r:
tensor([[0.3507, 0.7367],
        [0.5238, 0.9452]])

inverse sine of r:
tensor([[-0.3583, -0.8282],
        [-0.5513, -1.2383]])

Determinant of r:
tensor(-0.0544)

Singular value decomposition
torch.return_types.svd(
U=tensor([[-0.6024, -0.7982],
        [-0.7982,  0.6024]]),
S=tensor([1.3535, 0.0402]),
V=tensor([[ 0.4650, -0.8853],
        [ 0.8853,  0.4650]]))

Average and standard devation of r:
(tensor(0.2580), tensor(-0.6391))

Maximum value of r:
tensor(-0.3507)
